# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  release:
    name: Create Release and Upload Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CLI binary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_git_tag }}
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o kubectllama-linux-amd64 ./cmd/main.go
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o kubectllama-macos-amd64 ./cmd/main.go
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o kubectllama-windows-amd64.exe ./cmd/main.go
            
      - name: Upload assets
        if: steps.semantic.outputs.new_release_published == 'true'  
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_git_tag }}  # Use the tag from semantic-release
          files: |
            kubectllama-linux-amd64
            kubectllama-macos-amd64
            kubectllama-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}